# Numpy

* Numpy modülünü indirmek için cmd kısmında "pip install numpy" ile yükleyebilirsiniz

In [1]:
import numpy as np  # Numpy modülü eklendi ve kısayol için np adı verildi

# Numpy Nedir?
    -Bilimsel hesaplamalar için kullanılan bir python modülüdür.
    -Numerical Python'ın kısaltmasıdır.
    -Listelere benzer diyebiliriz ama listeden daha hızlı ve daha verimli çalışır

### Array Tanımlama

Array tanımlarken np.array([liste]) olacak şekile yazılır

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Range Tanımlama

Range işleminde np.arange(x,y,z) olacak şekilde yazılır.(x=başlangıç,y=bitiş,z=artış miktarı)

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b=np.arange(10,20)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
c=np.arange(10,20,2)
c

array([10, 12, 14, 16, 18])

# Zeros - Ones - Eye Tanımlama

Zeros 0 matrisi olarak düşünebiliriz

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Ones 1 matrisi olarak düşünebiliriz

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Eye ise birim matristir

In [13]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Linspace Listeyi Eşit Ayırma

Linspace işleminde np.linscape(a,b,c) olacak şekilde tanımlanır(a=başlangıç,b=bitiş,c=eşit parça bölme sayısı)

In [15]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [16]:
np.linspace(5,50,10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

Eğer eşit parça bölme sayısı verilmez ise otomatik olarak 50 parçaya böler (Default=50)

In [17]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

### Full Array

Full Array da ise np.full((a,b),c) şeklinde yazılır(a=satir,b=sütun,c=tek eleman)

In [18]:
np.full(3,7)

array([7, 7, 7])

In [19]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [20]:
np.full((3,3,2),7)

array([[[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]]])

### Random

Randomda rastele array sayısı verir.Eğer parametre verilmez ise 0-1 arasında float değer verir

In [21]:
np.random.rand()

0.29152678143186816

In [22]:
np.random.randn()

-0.8373615874809823

Eğer parametre verilirse verilen iki parametre arasında rastgele float değer döndürür

In [23]:
np.random.rand(1,10)

array([[0.29522057, 0.85197013, 0.04350424, 0.01456449, 0.35336129,
        0.69180524, 0.60615531, 0.96886045, 0.30938068, 0.00334568]])

In [24]:
np.random.rand(1,10,2)

array([[[0.6143016 , 0.45070975],
        [0.23028072, 0.78568339],
        [0.13739961, 0.84238353],
        [0.6951757 , 0.03851877],
        [0.66181553, 0.33401893],
        [0.26408836, 0.88128516],
        [0.94158563, 0.36950637],
        [0.2408115 , 0.98763046],
        [0.49543178, 0.26378008],
        [0.78864427, 0.62465009]]])

In [25]:
np.random.randn(3,3)

array([[-1.79479912,  0.34820696,  1.58611106],
       [ 0.03978048, -2.45438507,  0.24459319],
       [-0.26425813,  0.23022234,  1.14978185]])

randn yerine randint tanımlarken bu sefer float yerine integer rastele sayı üretir

In [26]:
np.random.randint(10)

6

In [27]:
np.random.randint(1,50)

4

In [28]:
np.random.randint(1,50,2)

array([26, 17])

In [29]:
np.random.randint(1,50,(2,2))

array([[17, 48],
       [21, 41]])

In [30]:
np.random.randint(1,50,size=(2,2))

array([[33, 21],
       [42, 22]])

### Reshape

Reshape işleminde array listesinin boyutunu biçimlendirir. np.arange(x).reshape(y,z) ---> x=y.z olmak zorundadır

In [31]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
np.arange(12).reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [33]:
np.arange(12).reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Numpy Biçimlendirme

In [34]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.ndim)  #Boyut Sayısı
print(a.shape) #Boyut Bilgisi
print(a.size)  #Toplam Eleman Sayısı
print(a.dtype) #Array Veri Tipi
a

2
(3, 3)
9
int32


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Determinant

Array'in determinantını hesaplamak için kullanılır

In [35]:
array=np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
determinant=np.linalg.det(array)
determinant

-9.51619735392994e-16

In [37]:
array=np.array([[4,2],
                [1,3]])

In [38]:
determinant=np.linalg.det(array)
determinant

10.000000000000002

### Array Birleştirmek

Verilen ikiden ve ikiden fazla arrayi birleştirmek için kullanılır(axis=0 --> dikey , axis=1 --> yatay)

In [39]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [40]:
x

array([1, 2, 3])

In [41]:
y

array([4, 5, 6])

In [42]:
np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6])

In [43]:
np.concatenate((x,y),axis=0)

array([1, 2, 3, 4, 5, 6])

In [44]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
np.concatenate((x,x,x))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
xxx=np.concatenate((x,x,x),axis=0)
xxx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
xxx.shape

(9, 3)

In [48]:
xxx=np.concatenate((x,x,x),axis=1)
xxx

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9]])

In [49]:
xxx.shape

(3, 9)