In [1]:
import numpy as np  #modül eklenir

### Numpy Eleman İşlemleri

In [2]:
a=np.random.randint(10,size=10)    #10 boyutlu 10'a kadar olan sayılar rastgele verildi

Arraylerde index işlemi array[a:b:c] şeklinde yazılır. (a=başlangıç,b=bitiş,c=artış miktarı)

In [3]:
a

array([7, 3, 7, 9, 5, 8, 6, 8, 8, 4])

In [4]:
a[0] #Arraylerde index sıralama 0'dan başlar.Yani ilk eleman 0.indextir

7

In [5]:
a[len(a)-1] #Son elemanı yazdırmak için listenin eleman sayısından 1 çıkarılıp hesaplanır

4

In [6]:
a[-1] # Daha kısa çözüm için index kısmına -1 yazılır

4

In [7]:
a[2:9] #Eğer başlangıç ve bitiş verilip artış miktarı verilmezse varsayılan olarak artış miktarı 1 olur

array([7, 9, 5, 8, 6, 8, 8])

In [8]:
a[2:9:3] #Eğer artış miktarı da verilirse istenilen değere göre artış miktarını yazdırır

array([7, 8, 8])

In [9]:
a[::-1] #Artış miktarı -1 yazıldığın listeyi tersten yazdırır

array([4, 8, 8, 6, 8, 5, 9, 7, 3, 7])

### Alt Kümelere Erişmek

Verilen array için array[x,y] şeklinde alt kümelere erişilir.(x=satir_index,y=sutun_index)

In [10]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a[1,1]  #1.index satırı,1.index sütunu

5

In [12]:
a[:2,1]  #2'ye kadar index satırı,1.index sütunu

array([2, 5])

In [13]:
a[:3,:2]  #3'e kadar index satırı,2'ye kadar index sütunu

array([[1, 2],
       [4, 5],
       [7, 8]])

Ayırılan bölgenin sayıları değiştirilebilir

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
a[1,1]  #İstenilen bölge ayrıldı

5

In [16]:
a[1,1]=99 #İstenin bölgeye yeni değer atandı

In [17]:
a

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

### Numpy İle Eleman İşlemleri

In [18]:
a=np.arange(10)

In [19]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a+10  #arraydeki tüm elemanlara 10 ekler

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
a-10  #arraydeki tüm elemanlardan 10 çıkarır

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [22]:
a*2  #arraydeki tüm elemanları 2 ile çarpar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
a/2  #arraydeki tüm elemanları 2 ile böler (float şeklinde)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [24]:
a//2 #arraydeki tüm elemanları 2 ye böler (int şeklinde)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int32)

In [25]:
a%2 #arraydeki tüm elemanların elemanlarının mod 2'sini alır

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [26]:
a**2 #arraydeki tüm elemanların karesini alır

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

İki ve ikiden fazla array ile de toplanır

In [27]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
b=np.arange(100,91,-1).reshape(3,3)
b

array([[100,  99,  98],
       [ 97,  96,  95],
       [ 94,  93,  92]])

In [29]:
a+b #İki array toplanır

array([[101, 101, 101],
       [101, 101, 101],
       [101, 101, 101]])

### Koşullu Eleman İşlemleri

Bir arraye verilen şarta göre elemanları filtreleme işlemidir

In [30]:
a=np.arange(10)

In [31]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a>5 #5 den büyük olanlar için True diğerleri için False değerini döndürür

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [33]:
a[a>5] #True değerler için filtreleme işlemi yapar

array([6, 7, 8, 9])

In [34]:
a[a>=5] #5 ve 5'den büyük olan sayıları filtreler

array([5, 6, 7, 8, 9])

In [35]:
a[a<3]  #3 den küçük olanlar sayısını filtreler

array([0, 1, 2])

In [36]:
a[a<3]  #3 ve 3 den küçük olan sayıları filtreler

array([0, 1, 2])

In [37]:
a[a==7]  #7'ye eşit olan sayıyı filtreler 

array([7])

In [38]:
a[a!=7] #7'ye eşit olmayan sayıları filtreler

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

### All ve Any İşlemleri

In [39]:
a=np.arange(10)

In [40]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Any işleminde en az birini sağlarsa True değerini döndürür.Eğer sağlamazsa False değerini döndürür

In [41]:
np.any(a<5)

True

In [42]:
np.any(a>10)

False

All işleminde hepsini sağlarsa True en az birini sağlamazsa False değerini döndürür

In [43]:
np.all(a>=0)

True

In [44]:
np.all(a>1)

False